# Generated by Django 6.1 on 2026-08-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=50, unique=True)),
                ('customer', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('recovery_probability', models.IntegerField(default=0)),
                ('recommended_action', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
