# Generated by Django 6.1 on 2026-08-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_age_days',
            field=models.IntegerField(default=365),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_history',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='UPI', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='previous_failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='recovered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recommended_action',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
